### ISSUE TITLE
Support For 'Youtube-Music' By 'th-ch'

### ISSUE THREAD

**Issue by RajStartsHere** [topik/youtube-music-obs-widget#10]
Can You Please Try For Getting This Plugin Work From [Youtube-Music](https://github.com/th-ch/youtube-music) By [th -ch](https://github.com/th-ch)
I Would Really Appreciate It

**Comment by topik** [comment]
I am sorry, but I tried and they did not approved my plugin for more than a year (afaik), I don't think I am gonna waste my time in the near future again🙂

**Comment by RajStartsHere** [comment]
@topik I Think You Are Right

**Comment by JellyBrick** [comment]
> I am sorry, but I tried and they did not approved my plugin for more than a year (afaik), I don't think I am gonna waste my time in the near future again🙂

We clearly said that we needed to rebase it because the entire structure of the application had changed.
https://github.com/th-ch/youtube-music/pull/1120#issuecomment-2412889994

**Comment by JellyBrick** [comment]
> I am sorry, but I tried and they did not approved my plugin for more than a year (afaik), I don't think I am gonna waste my time in the near future again🙂

@topik We clearly said that you needed to rebase it because the entire structure of the application had changed.
on Oct 7, 2023: https://github.com/th-ch/youtube-music/pull/1120#event-10581282608
Once again, on last Oct 14, we asked: https://github.com/th-ch/youtube-music/pull/1120#issuecomment-2412889994

**Comment by JellyBrick** [comment]
We've been reviewing it periodically for over a year, obviously, and you've done nothing with our feedback.

**Comment by topik** [comment]
I pushed the branch in April 2023, you asked for rework in October 2025. I did not see any requests by @JellyBrick (or anyone else) so If you were waiting for any response, maybe ask first 🙈

**Comment by ArjixWasTaken** [comment]
JellyBrick did add a label `need-rebase` back in 07/10/2023, assuming you look at your github notifications it should have been enough

albeit, no message was sent back then, so it ain't really your "fault"

**Comment by JellyBrick** [comment]
We requested the rebase in October 2023...
https://github.com/th-ch/youtube-music/pull/1120#event-10581282608

Anyway, would you be available to rewrite that plugin...?
If you rewrite the plugin, we can review it right away.

**Comment by topik** [comment]
sure guys, I'll do it when I have some free time. And yeah, maybe I missed the notification, anyway I am not mad or anything nor I blame anyone.
