### ISSUE TITLE
YTMDesktop updated to 2.0 and broke the widget

### ISSUE THREAD

**Issue by DeFlanko** [topik/youtube-music-obs-widget#5]
[YTMDekstop 2 missing Remote Control](https://github.com/ytmdesktop/ytmdesktop/issues/1279)

![image](https://github.com/topik/youtube-music-obs-widget/assets/5233969/421c6b44-8ecc-49e3-927b-dee15f9c9fbf)

**Comment by topik** [comment]
Should be fixed. Let me know if its not gonna work for you. Happy streaming 🙂

**Comment by DeFlanko** [comment]
checking now!

**Comment by DeFlanko** [comment]
Fixed!

![image](https://github.com/topik/youtube-music-obs-widget/assets/5233969/cf27628f-c07e-4f53-90dc-2e00ce8df024)
