### ISSUE TITLE
how to delete YTMD ??

### ISSUE THREAD

**Issue by THEROBINATOR2077** [topik/youtube-music-obs-widget#7]
I have stopped using YTMD but when I open YTMD I get this alert page. What can I do to stop it from opening?     
![image_2024-03-11_124443104](https://github.com/topik/youtube-music-obs-widget/assets/132782590/b8cd8004-4a8b-4501-bf3c-ea96255686de)

**Comment by topik** [comment]
When you open YTMD? That's hard to believe. Don't you think, when you open OBS? Just delete the widget from OBS and it will not show again.
